jellyfin/jellyfin.org

- .github/workflows/deployment.yml
- docusaurus.config.js
- package-lock.json
- package.json
Upgrades docusaurus to the latest 2.0 version
> Upgrade docusaurus

- docusaurus.config.js
* Adds the logo to the footer
* Uses simple footer layout with fewer links
> Update footer layout

- src/components/ContributorGuide.tsx
- src/pages/contribute.tsx
This is mostly identical to the existing page, just ported here.
> Add contribute page

- src/pages/downloads.tsx
> Add downloads page

- src/pages/contribute.tsx
- src/pages/downloads.tsx
I missed updating this class name in a couple places :eyes:
> Fix incorrect class names

- src/pages/andtv-privacy.md
Adds https://jellyfin.org/andtv-privacy.html
> Add androidtv privacy page

- src/components/HomepageFeatures.tsx
This fixes the overflow on the home screen. The container class was incorrect on this section.
> Fix invalid container class

- package.json
- scripts/copy-rss-feed.js
> Add postbuild script to copy rss feed

- .github/workflows/build.yml
:crossed_fingers: This will fix this: https://github.com/jellyfin/jellyfin.org/runs/7891806479?check_suite_focus=true
> Fix permissions for GH pages workflow

- docusaurus.config.js
- package-lock.json
- package.json
> Add redirects plugin

- docs/general/administration/hardware-acceleration.md
- docs/general/clients/index.md
- docs/general/contributing/index.md
- src/components/ContributorGuide.tsx
Fixes #107.
Was uncertain about the change of `Collection of useful links and information` – so have removed for now. Please advice and I'm happy to resolve. :)
> Update Documentation Links

- src/components/downloads/DownloadDetails.tsx
- src/data/downloads.tsx
> Fix capitalization and Fedora status

- docusaurus.config.js
- package-lock.json
- package.json
This seems to be working, but is difficult for me to verify since I have the font available locally.
> Add missing font resources

- docusaurus.config.js
- package-lock.json
- package.json
- src/css/custom.css
Search field in navbar
Searching in navbar
Search results page
> Add search plugin

- src/pages/downloads/docker.tsx
- src/pages/downloads/index.tsx
- src/pages/downloads/linux.tsx
- src/pages/downloads/macos.tsx
- src/pages/downloads/windows.tsx
> Add OS specific download pages

- src/pages/downloads/index.module.css
- src/pages/downloads/index.tsx
Just cleans up mobile styles a bit.
| Before | After |
|---|---|
| ![Screen Shot 2022-08-30 at 00 46 17](https://user-images.githubusercontent.com/3450688/187351934-06ff523f-23ea-4b6e-aaed-d586742780f6.png) | ![Screen Shot 2022-08-30 at 00 45 53](https://user-images.githubusercontent.com/3450688/187352074-a56249a2-d5e5-4e1a-956f-e9231e7f20b9.png) |
> Cleanup stable pill layout

- src/components/common/Hero.css
- src/components/home/CallToAction.modules.css
- src/components/home/CallToAction.tsx
- src/css/custom.css
- src/pages/index.tsx
Just a little cleanup of the styling of the hero and cta sections of the home page.
| Before | After |
|---|---|
| ![Screenshot 2022-08-30 at 12-21-09 The Free Software Media System Jellyfin](https://user-images.githubusercontent.com/3450688/187489165-cf63bde1-1459-4a97-9ba7-d82f4acbe660.png) | ![Screenshot 2022-08-30 at 12-22-02 The Free Software Media System Jellyfin](https://user-images.githubusercontent.com/3450688/187489287-4652b08b-8def-4961-96cd-5d53806686b0.png) |
| ![Screenshot 2022-08-30 at 12-22-54 The Free Software Media System Jellyfin](https://user-images.githubusercontent.com/3450688/187489458-9c746eb2-9dc3-40f0-8a52-cb45772cf44a.png) | ![Screenshot 2022-08-30 at 12-23-41 The Free Software Media System Jellyfin](https://user-images.githubusercontent.com/3450688/187489594-8a5 …
> Cleanup styling of home page hero and cta sections

- src/components/common/Hero.css
- src/pages/index.tsx
Fixes an issue with the alignment of the buttons on the hero of the home page.
> Fix button alignment on home page hero

- src/components/contribute/ContributorGuide.tsx
- src/components/home/CallToAction.tsx
- src/pages/contribute.tsx
- src/pages/index.tsx
Link components have a better loading experience than normal anchors for local links. (Anchors cause a full refresh of the page.)
> Use <Link> not <a>

- package-lock.json
- package.json
- src/components/home/HomepageFeatures.tsx
- src/css/custom.css
* Restores the "What is Jellyfin?" copy from the current site
* Adds swiper to scroll through features on mobile
> Update home screen features section

- src/components/home/BuiltByVolunteers.modules.css
- src/components/home/BuiltByVolunteers.tsx
- src/components/home/CallToAction.module.css
- src/components/home/CallToAction.tsx
- src/components/home/FreeSoftware.modules.css
- src/components/home/FreeSoftware.tsx
- src/components/home/LandingSection.module.css
- src/components/home/MoreClients.tsx
- src/css/custom.css
* Moves landing sections styles to a shared css module
* Move common landing section logo styles to css module
* Fix css module file names (should be `*.module.css` **not** `*.modules.css`)
> Cleanup landing section styles

- src/components/home/ClientSection.tsx
- src/components/home/HomepageFeatures.tsx
- src/png.d.ts
Fixes a few minor miscellaneous issues:
* Prevent orphaned word in clients heading
* Fix features section class
* Fix type error when importing png files
> Home screen cleanup

- src/components/downloads/DownloadDetails.tsx
- src/data/downloads.tsx
* Fixes capitalization of FFmpeg in the features enum
* Fixes debuntu instructions showing under arch
* Adds support for closing install instructions
> Fix downloads issues

- src/components/home/InActionSection.tsx
* Enable autoplay for screenshot slides
* Enable clicking on pagination bullets for screenshot slides
> Enable autoplay for screenshot slides

- docusaurus.config.js
Related to https://github.com/jellyfin/jellyfin-web/pull/3803
> Add subtitle docs page redirect

- docs/general/server/media/comics.md
Fixes issue https://github.com/jellyfin/jellyfin.org/issues/171
> Fixes broken Note in Comics doc

- docs/general/administration/troubleshooting.md
- docs/general/clients/kodi.md
Ports the changes from https://github.com/jellyfin/jellyfin-docs/pull/700 and https://github.com/jellyfin/jellyfin-docs/pull/705 here.
Related to https://github.com/jellyfin/jellyfin.org/issues/89
> Port jellyfin-docs updates

- .github/CODEOWNERS
I think it makes sense for these specific files to require a review from the core team and project lead.
> Add CODEOWNERS for specific files

- src/css/custom.css
- src/data/clients.ts
- src/data/platform.ts
- src/pages/clients/index.module.css
- src/pages/clients/index.tsx
Adds device and platform filtering options to the Clients page.
**Default (Filters Collapsed)**
**Filters Applied**
**Filters Applied w. No Results**
Fixes #133
> Add client filtering options

- src/data/downloads.tsx
Fixes a small issue with the debian instructions producing an invalid sources file
> Fix debian sources architecture

- docs/general/clients/codec-support.md
> Fix codec support page formatting

- docusaurus.config.js
Removes the announcement banner at the top of the site
> Remove announcement bar

- src/components/clients/ClientDetails.tsx
- src/data/clients.ts
Adds Swiftfin to the client page as an "official beta"
> Add Swiftfin to client list

- docs/general/server/media/external-files.md
Syncing https://github.com/jellyfin/jellyfin-docs/pull/715 to this repo
> Expand external file flag documentation

- docusaurus.config.js
- static/CNAME
Update the site url in the docusaurus config and CNAME file
**NOTE:** This should probably not be merged until immediately before we make the necessary DNS changes
> Update site url configuration

- docs/general/server/media/movies.md
Update supported movie special feature types to match what is currently supported in code.
> Update Movie special features

- docs/general/clients/css-customization.md
Copy of https://github.com/jellyfin/jellyfin-docs/pull/723 to correct repo
Since I was looking for this and I didn't find it in the docs, I added to the docs after I found out.
If you have any remarks, let me know
> Added documentation for styling count indicators

- docs/general/server/media/shows.md
Document Show extras functionality introduced in 10.8. Adapted from the Movies page.
> Update Show Extras

- src/components/contact/MatrixCard.tsx
Adds a link to the new matrix room for ui/ux development discussions
> Add link to ui/ux matrix room

- src/components/contact/MastodonCard.tsx
- src/pages/contact.tsx
Adds Mastodon to the list of social media accounts.
> Add Mastodon option

- src/components/contact/ContactCard.scss
Adds the missing CSS for the button to have colour.
> Add Mastodon CSS Colours

- blog/2022/12-24-android-tv-15/index.mdx
- Fix alt text for picture viewer screenshot
- Replace RTL abbreviation with right-to-left for readers that don't know the abbreviation.
> Update Android TV 15 post

- blog/2022/12-29-swiftfin/index.mdx
Adds the introductory post for Swiftfin availability.
> Add Swiftfin post

- blog/2022/07-25-roku-v1.5.0.md
Adds release and roku tags to older Roku 1.5.0 blog post.
> Add tags to older Roku blog post

- docs/general/networking/iis.md
- docs/general/networking/ipban.md
Added a basic IIS config and IPBan
> Some windows alternatives

- docs/general/installation/linux.md
See #367 for full details.
I've grepped the documentation to ensure all instances of this issue have been fixed (there were only the 2).
Edit: Feel free to make any edits, and please @mention me if you need anything else from my end.
> Fix GPG key URIs in docs

- docs/general/server/plugins/index.md
I am told by user's on the Jellyfin discord that this issue is resolved.
> remove windows note about unresolved permissions

- docs/general/server/plugins/index.md
I'm not sure if we're allowed to list our plugins here. If not, feel free to close the PR.
For more information about Themerr see my reddit post. -> https://www.reddit.com/r/jellyfin/comments/10tjvf3/introducing_themerr
> Add Themerr to third party plugin list

- docs/general/server/media/movies.md
Cleaned up 3D Movies information for added clarity and corrected an error in the examples.
> Update 3D Information in movies.md

- src/data/clients.ts
- The purpose of this PR is to add my client for Jellyfin, JellyBook to the client list
- I am a little unsure of if there is a order in which the list is in since I didn't see any pattern to how the list was organized so if I need to change it, let me know
> Add JellyBook to list of clients

- docs/general/server/media/movies.md
Fixing my own superfluous comma and moving a parenthetical to a standalone sentence for clarity.
> Clarity update for movies.md

- docs/general/networking/haproxy.md
Validated with HAProxy 2.7.2 and Jellyfin 10.8.9
> Fix forwardfor header and add health check

- docs/general/administration/hardware-acceleration.md
This PR adds a section into https://jellyfin.org/docs/general/administration/hardware-acceleration/#va-api-hardware-acceleration-on-debianubuntu to describe how the VA-API can be enabled on Kubernetes. The principle is the same as for Docker except for some small minor details.
The Kubernetes documentation on devices is very confusing, and stackoverflow offers very little help on this, so I thought this might be useful for someone.
I use this exact configuration and VA-API playback on my AMD 5600G works perfectly. I can see in the logs that `/usr/lib/jellyfin-ffmpeg/ffmpeg` starts with `vaapi=va:/dev/dri/renderD128` without any error. Video and audio works. I have also checked on the host system and the CPU usage was close to 1% (I did not check GPU usage, but that should be enough of a …
> Add documentation for VA-API on Kubernetes for Linux

- src/data/clients.ts
Hi 👋
I would like to add my open source project to the list of available clients.
Please let me know if I should change anything or if the commit message is fine.
> Add client to "Clients" page

- docs/general/server/media/shows.md
Document existing functionality for stacking video files. Same holds for movies and any other video types.
> Document episode file stacking

- docs/general/administration/hardware-acceleration/intel.md
- Add a tiny fix for intel docs - The indices were changed from **3 and 4** to **2**.
> Add a tiny fix for intel docs

- docs/general/administration/hardware-acceleration/amd.md
- docs/general/administration/hardware-acceleration/intel.md
- docs/general/administration/hardware-acceleration/nvidia.md
- Add some tweaks and trim the unused card*
> Add some tweaks and trim the unused card*

- docusaurus.config.js
- package-lock.json
- package.json
This is basically #396 but backported to the master branch so rebasing the developer branch will be easier after renovate updates the NPM packages.
> Replace Docusaurus presets with manual plugin & theme configuration

- blog/2023/03-23-roku-v164/index.mdx
- blog/2023/03-31-roku-v164/index.mdx
Create a blog post for the upcoming Roku 1.6.4 release.
**Don't merge until we receive confirmation from Anthony.**
> Create blog post for Roku 1.6.4 Release

- docs/general/administration/hardware-acceleration/intel.md
- docs/general/administration/hardware-acceleration/nvidia.md
- Update NVENC sessions limit for 530+ driver
- Update docs for `enable_guc_loading` params
> Update NVENC sessions limit for 530+ driver

- docs/general/contributing/development.md
- docs/general/installation/source.md
> Update to .NET 7

- docs/general/administration/hardware-acceleration/intel.md
Fixed Typo in Kubernetes section
> Fixed typo in Kubernetes section

- blog/2023/05-14-android-v250/index.mdx
I left in some TODOs where I wasn't sure yet whether to include them or not.
Otherwise, I'm looking forward to any feedback.
> Add blog post for Jellyfin Android 2.5.0 release

- src/components/contact/RedditCard.tsx
Disables the Reddit link with a short message.
> Disable Reddit Link

- src/components/contact/MatrixCard.tsx
- Fix Matrix vue link
- Fix Matrix roku link
> Fix matrix contact links

- src/data/clients.ts
Hi there! I run an audio streaming app for Jellyfin called Fintunes, and I'd like that to be a part of the Jellyfin website as well. You can find more information about the project on the website (https://fintunes.app) or on the GitHub repository (https://github.com/leinelissen/jellyfin-audio-player). 
I look forward to hearing from you!
Lei
> feat: add Fintunes to downloads

- docs/general/installation/index.mdx
Add Warning message for FreeBSD so people know where to ask for support when things go wrong.
> Add FreeBSD warning message

- src/data/clients.ts
See: https://github.com/KGT1/jellyfin-discord-music-bot
> KGT1's discord bot is unmaintained

- docs/general/quick-start/windows.md
changed "poperly" to "properly"
> Fixed typo

- docs/general/networking/nginx.md
Whitelist gstatic.com instead of specific paths because they change over time.
> Fix Nginx CSP for Chromecast

- docs/general/administration/configuration.md
This PR is intended to go with [jellyfin-web/#4863](https://github.com/jellyfin/jellyfin-web/pull/4863/).
I was asked to move the link into code and shorten the text.
Currently there is info included in strings in web that isn't in the docs. This PR will document those things.
> Improve fallback fonts documentation

- docs/general/administration/hardware-selection.md
Eliminate potential confusion that might be caused by punctuation.
> Make wording slightly better in Hardware Selection

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
Upgrade to latest LTS, Docusaurus 3 also needs 18>=
> Use Node 20 in CI

- package-lock.json
- package.json
- tsconfig.json
> Upgrade to Docusaurus 3

- src/scss.d.ts
Fixes some red lines in VSCode
> Add type definition for scss files

- package-lock.json
- package.json
- src/components/home/HomepageFeatures.tsx
- src/components/home/InActionSection.tsx
Last one, update imports for Swiper
> Upgrade to Swiper 11

- blog/authors.yml
Adds a title tag to my author entry.
> Add author title to myself

- src/data/clients.ts
Supersonic is a desktop music player for Subsonic and Jellyfin servers
> Add Supersonic to clients list

- docs/general/server/plugins/index.md
This PR adds LizardByte's third party plugin manifest AND alphabetizes existing plugins and repositories.
> docs: add LizardByte plugin repository and alphabetize

- docs/general/administration/hardware-selection.md
Update codec support table in hardware selection guide, rework to reduce clutter
> Update codec support info for Apple M3 Family of SOCs

- docs/general/installation/container.md
use AutoUpdate option instead of label in podman systemd example
> use AutoUpdate option instead of label in podman systemd example

- docs/general/installation/container.md
add docs for using hardware acceleration with rootless podman containers
> add docs for using hardware acceleration with rootless podman containers

- docs/general/server/plugins/index.mdx
Themerr now supports theme songs for Shows/Series.
> docs(plugins): update description of Themerr

- docs/general/server/metadata/nfo.md
We've been missing the column closing pipe for two years but the linter is just now complaining.
> Add missing column for linter

- docs/general/server/media/shows.md
> Fixed typo that bothered me

- docs/general/administration/hardware-acceleration/amd.md
- docs/general/administration/hardware-acceleration/index.md
- docs/general/administration/hardware-acceleration/intel.md
- docs/general/administration/hardware-acceleration/nvidia.md
- Update some outdated HWA docs
> Update some outdated HWA docs

- docs/general/administration/hardware-acceleration/index.md
> Fix typo in "Raspberry"

- docs/general/administration/hardware-acceleration/amd.md
- docs/general/administration/hardware-acceleration/intel.md
- Inform users of known issues in the latest Windows graphics drivers
They have been asked many times. And it seems like Intel and AMD will need several iterations of driver versions to fix them.
> Inform users of known issues in the latest Windows graphics drivers

- docs/index.md
Removes invalid link 
Refs https://github.com/jellyfin/jellyfin.org/pull/697
> Remove unraid reference

- docs/general/networking/nginx.md
Correcting and updating instructions for nginx proxy manager based on user feedback.  Verified in test setup.
> Correcting and updating instructions for nginx proxy manager

- docusaurus.config.ts
- src/components/contact/ContactCard.scss
- src/components/contact/MastodonCard.tsx
- src/components/contact/XCorpCard.tsx
- src/pages/contact.tsx
Twitter is no more. We should use X now.
> Converted Twitter to X

- content/developers/docs/api/authorization.md
(targets the developers branch)
Update to latest changes from https://gist.github.com/nielsvanvelzen/ea047d9028f676185832e51ffaf12a6f
> Update authorization documentation to latest gist revision

- docs/general/server/media/shows.md
- Updated instances of "series" to "Series Name"
- Updated flat folder structure to use Season folders in examples
> Updated "Series" placeholder and removed flat show episode structure from examples

- docusaurus.config.ts
- package-lock.json
- package.json
Enables mermaid support for Docusaurus to allow charts and diagrams in the docs
> Enable mermaid module to allow charts and diagrams

- docs/general/administration/hardware-acceleration/intel.md
Adding clarifying steps for common Intel HWA questions on Debuntu platforms.
> Updating and clarifying Intel HWA steps on Debuntu

- docs/general/server/media/movies.md
Add a warning against ISO files
As for the admonition, I don't really see a better way to fit it into this page without using one. This page is already littered with them and would require a cleanup to avoid things not in admonitions being drowned out.
> Add ISO file warning

- src/data/downloads.tsx
Makes the output nicer when people run it.
> Use -s/-q for Curl command in Debuntu

- docs/general/administration/hardware-acceleration/index.md
- docs/general/administration/hardware-acceleration/rockchip.md
- docs/general/administration/hardware-selection.md
- Add HWA docs for Rockchip VPU (RKMPP, feat. RK3588)
> Add HWA docs for Rockchip VPU (RKMPP, feat. RK3588)

- docs/general/testing/index.md
- docs/general/testing/server/index.md
- docs/general/testing/upgrades.md
- src/pages/downloads/server.tsx
To and from Unstable including more details on release testing.
> Add documentation of upgrading and downgrading

- blog/2024/03-25-testing-10.9.0/index.mdx
(unrelated formatting changes made automatically by VSCode per the repository vsc configuration)
> Add update to "Testing 10.9.0" post

- docs/general/installation/linux.md
Added a NixOS section to the Linux install documentation.
> doc: linux.md: Added NixOS section.

- docs/general/networking/traefik2.md
description says it should be 1, but the value is 0
> fix traefik v2.x doc: x-xss-protection description/value mismatch

- blog/2024/05-11-jellyfin-release-10.9.0/index.mdx
And fix the date because that bugged me.
> Add note about INVARIANT globalization

- docs/general/administration/hardware-selection.md
> Fix typo in hardware-selection.md

- docs/general/networking/nginx.md
Deprecated X-XSS-Protection header
> Deprecated X-XSS-Protection header

- src/data/pluginRepositories.ts
The title says it all. The URL changed.
> Edit ShokoAnime's Repo manifest URL

- docs/general/server/media/shows.md
Addresses issue: https://github.com/jellyfin/jellyfin/issues/7905
> docs: Directly state, that imdbid is not supported for shows

- docs/general/server/media/movies.md
menus are not support -> menus are not supported
> fix grammar mistake

- docs/general/administration/hardware-selection.md
Fix a broken link in hardware selection guide introduced in https://github.com/jellyfin/jellyfin.org/pull/1053
> Fix broken link

- docs/general/clients/index.mdx
Inserting missing parenthesis on clients documentation.
> Inserting missing parenthesis

- docs/general/clients/css-customization.md
Add "Scyfin" theme to list of community themes
> Add "Scyfin" theme to list of community themes

- docs/general/administration/storage.md
Continuation of https://github.com/jellyfin/jellyfin.org/commit/0c6c85f8347650ca6c77ef870041cfbce61658d0
> Remove remaining reference to animostiy22's repo

- docs/general/community-standards/chat.md
To avoid discord in the chat rooms.
> Documentation update for chat room rules

- docs/general/testing/web/index.md
People not-so well versed with GH might not know what a PR is.
I didn't thought about this in code review, sorry!
Feel free to close it though, since it can also be argued that if you tinker between PRs you understand what "PR" is.
> refactor: replace PR with Pull Requests

- docs/general/server/media/music.md
* Inspired by @JustJamie4realz work -> https://github.com/jellyfin/jellyfin.org/pull/1054
Signed-off-by: Morgan Davies <25231953+M-Davies@users.noreply.github.com>
> docs: add lyrics documentation

- docs/general/administration/hardware-acceleration/nvidia.md
Adjusting nvidia docker compose example based on multiple forum troubleshooting threads.
> Adjusting nvidia docker compose example

- docs/general/administration/hardware-selection.md
Simple typo fix in the documentation on recommended hardware.
(Panning -> Planning)
> Fix typo panning -> planning

- src/components/common/PlatformIcon.tsx
> Use Windows icon from Font Awesome

- docs/general/networking/dlna.md
Fixes https://github.com/jellyfin/jellyfin-plugin-dlna/issues/91
> Update DLNA debugging documentation

- docs/general/clients/jellyfin-vue.md
I've made some backward compatible changes to the images and the old one will work just fine as well, but this one is less verbose.
> feat(clients/vue): less verbose custom webserver setup

- docs/general/server/media/movies.md
documents https://github.com/jellyfin/jellyfin/issues/12129
> update movie version sorting

- docs/general/installation/truenas.md
Opening this PR to fix the requested changes in review by Felix.
Link to first PR: https://github.com/jellyfin/jellyfin.org/pull/1228
> Fixing reviewed Truenas Scale document.

- src/components/contact/MatrixCard.tsx
Update the `Matrix Card` to contain the `jellyfin-hwa-tool` Development Room.
> Add hwa-tool room to MatrixCard.tsx

- docs/general/administration/hardware-acceleration/amd.md
- docs/general/administration/hardware-acceleration/intel.md
Configuratoin to Configuration
> Fix Typo in docs

- docs/general/clients/index.mdx
According to a previous conversation on matrix
Question:
The guideline says `In particular, the client must **NOT** engage in, encourage, or facilitate piracy.`
Does that include integration with the *arr stack, jellyseerr or other tools commonly used for media acquisiton?
> Update client guidelines according to previous conversations in matrix

- blog/2025/01-25-efcore-and-me/index.mdx
I guess these are the correct numbers? CC @JPVenson @joshuaboniface
> Fix unstable EFCore version numbers

- docs/general/server/live-tv/setup-guide.md
As I mentioned on https://github.com/jellyfin/jellyfin.org/issues/1293, so that people don't waste their time.
> Added note of deprecation to LegalStream

- docs/general/administration/troubleshooting.md
Fix 2 broken links on the troubleshooting page.
> Fix broken links

- blog/2025/04-15-xbox-0.9/index.mdx
> fix-typo-slash

- docs/general/administration/hardware-acceleration/intel.md
- docs/general/administration/hardware-selection.md
https://github.com/jellyfin/jellyfin/issues/13944
> add warning for arc b series rebar

- docs/general/post-install/_category_.yml
Here is another pull request because venson couldn't wait
> Add missing hyphen

- docs/general/installation/macos.md
The menu bar menu says "Launch", not "Launch Web UI"
> Launch Web UI --> Launch

- docs/general/server/settings.md
Adds documentation about the splash screen image feature.
> Add splash screen documentation

- docs/general/contributing/development.md
The server is now using .NET 9.
Updating the development.md file to reflect that change.
> Update development.md - Jellyfin is now developed in .NET 9

- blog/2020/03-04-kodi-0-5-0.md
- docs/general/post-install/transcoding/hardware-acceleration/intel.md
- docs/general/post-install/transcoding/hardware-acceleration/rockchip.md
make markdown lint happy so CI won't fail
https://github.com/jellyfin/jellyfin.org/actions/runs/15104637525/job/42451145290
> make markdownlint happy

- docs/general/installation/advanced/truenas.md
- docs/general/post-install/networking/3_dlna.md
fix two faulty references to the old networking guide.
Found by @felix920506
> fix networking refferences

- docs/general/installation/advanced/manual.md
> update linux portable download link to 10.10.7

- docs/general/about.md
- docs/general/clients/_category_.yml
- docs/general/community-standards/_category_.yml
- docs/general/contributing/_category_.yml
- docs/general/faq.md
- docs/general/quick-start.md
- docs/general/server/_category_.yml
- docs/general/style-guides/_category_.yml
- docs/general/testing/_category_.yml
- docs/index.md
- redirects.ts
Creates a new version of the quick start guide and updates sidebar ordering
> Recreate quick start guide

- src/data/clients.ts
> Bump JF for Xbox

- docs/general/server/media/movies.md
Thanks to @ HeuRea for reporting this on our Discord!
> smoll typo fix

- docs/general/installation/container.md
Updated version of #1207 
Old PR has been closed due to being unmaintained and now entirely replaced by this PR.
All discussion about the change should move to this - actively maintained - PR.
Adding a note to the docker installation guide on how to replace placeholders!
> add uid:gid note
