jellyfin/jellyfin.org

src/css/custom.css
Currently these are white text on a white background... which is not great. A good example of this is [this post](http://next.jellyfin.org/posts/jellyfin-apt-key). This change reuses the same background color from the code blocks for the inline code.
=> Fix background color for inline code elements

.vscode/extensions.json, .vscode/settings.json
Fixes the issue mentioned in #80 by adding prettier as a recommended vscode plugin and using it for the default formatter.
=> Fix vscode not using prettier for formatting

src/components/ClientDetails.css, src/components/ClientDetails.tsx, src/components/Pill.tsx, src/components/PlatformIcon.tsx, src/css/custom.css, src/data/clients.ts, src/pages/clients.tsx
Data was sourced from https://jellyfin.org/clients/, https://jellyfin.org/docs/general/clients/index.html, and individual project repositories. 
Any clients that did not meet the WIP requirements described in https://github.com/jellyfin/jellyfin-meta/discussions/27 were excluded. There had been some discussion about whether in-development clients should be included or not, so I have excluded them for now. I think they could probably be added to the "All Clients" listing with a badge indicating their status though. The most notable example of this would probably be Swiftfin.
Some clients were difficult to categorize into device types and platforms... so additional options might be needed there.
There is some groundwork for including additional filtering options, but I think I'm going to …
=> Add clients page

.github/workflows/build.yml
Untested but should work fine. Additional changes need to be made after merge (and if the build works):
1. Change the repository settings to use GH actions for page deployment
2. Delete the gh-pages branch
3. Additionally, Renovate will make a PR to pin the version
See also https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site
=> Use official deploy pages action

.github/workflows/build.yml
It looks like we need a few different steps for the GH pages action to work. This is mostly based on the starter workflows: https://github.com/actions/starter-workflows/blob/main/pages/nextjs.yml
=> Update GH pages deploy action

docusaurus.config.js, src/css/custom.css
* Fixes the color mode which fixes the color of a lot of controls that were very difficult or impossible to see previously
* Removes the `15px` font size which caused menu items to be too small on mobile (also better to honor browser font size for accessibility)
* Removes `optimizeLegibility` because this is set by default in docusaurus
* Moves base line height to css variable
* Reorganizes css variables for clarity
* Removes active pill background color since the dark mode fix sets a background color
**Before:**
**After:**
=> Style fixes

src/css/custom.css, src/data/clients.ts, src/pages/clients/all.tsx, src/pages/clients/index.tsx
Adds a dedicated page for listing all clients `/clients/all` this helps with searchability and linking.
Also includes a minor update to the Android TV description to mention Fire TV.
=> Add dedicated page for all clients listing

docusaurus.config.js, src/pages/downloads/index.tsx
Adds the release badge to the top of the downloads page and the footer (on all pages).
Fixes #92
=> Add release badge

docs/general/networking/index.md
This seems like a weird DocFX specific link format... I didn't find any other instances of it.
=> Fix broken monitoring link

src/data/downloads.tsx
Recently, Debian-based distributions have switched to using the deb822
configuration format for APT sources by default.
This feature was first released in APT 1.1.
So, deb822-formatted sources have been supported since...
* Debian 9
* Ubuntu 16.04
Additionally, it is no longer recommended to globally add repository GPG
keys to APT's configuration. Instead, keys should be stored in
/etc/apt/keyrings and referenced only by the sources signed by them.
See: https://wiki.debian.org/DebianRepository/UseThirdParty
See: https://salsa.debian.org/apt-team/apt/-/commit/81460e32961bb0b9922bf8a1a27d87705d8c3e51
=> Modernize APT configuration for Debian & Ubuntu

docusaurus.config.js, src/components/home/InActionSection.tsx, src/css/custom.css, src/css/swiper.css
* Moves swiper customization to a separate css file
* Use pagination instead of navigation for screenshot slides
* Fixes margin issue due to browser styles of `<figure>`
* Changes active swiper to use `#eee` instead of `#fff` because I thought it looked a little better, but I am not a designer so :man_shrugging:
=> Use swiper pagination for screenshots

.github/workflows/lint.yml, .markdownlint.yaml, blog/2021/04-12-mirrorbits-cdn.md, docs/general/community-standards.md
The config is copied from the current jellyfin-docs repository because most content is from there. Two files contained some problems, one of them was a blog post in which I just disabled the linting.
Right now mdx files are not linted, I'm not sure if we want to add those.
=> Add markdownlint workflow

src/components/home/InActionSection.tsx, src/pages/contribute.module.css, src/pages/contribute.tsx
(Ignore the white background in the contributor graph... that seems to be an issue with Firefox loading mixed content that shouldn't be present when the site is served over https)
=> Add sponsors to contribute page

docusaurus.config.js
Blog search results seem to be taking priority over others and I suspect they won't be what most people are looking for on the site, so I think it is best to disable them until we can possibly provide some ranking/weighting to the search results.
=> Disable search indexing of blog posts

docs/general/getting-help.md
Updates the getting help page in the documentation to just reference the main contact page instead of duplicating information.
Fixes #170
=> Update the getting help documentation to reference the contact page

.vscode/extensions.json
This should help users that are not 100% familiar with markdown or the linter rules by showing error lines in VSCode.
Also reformatted the file because settings.json enables formatOnSave and prettier is set as default formatter and wants everything on one line...
=> Add DavidAnson.vscode-markdownlint as recommended workspace extension

src/pages/downloads/index.tsx
Just a minor cleanup to avoid multiple `.filter()` calls.
=> Combine download filters

docs/general/administration/installing.md, src/data/downloads.tsx
Some minor changes.
For macOS, though we do bundle FFmpeg, it's not the custom one that we have for our other platforms. It still works well, but it doesn't have some of the minor keyframe fixes, chromaprint, etc.
For Windows, we have not provided an x86 version in a long time, so I just removed the mention from the header.
=> Update OS Details

README.md
I couldn't think of anything better to put in its place, so I just axed this text. :sweat_smile:
=> Remove reference to next.jellyfin.org in README

src/data/clients.ts
Adds Jellyfin Vue to the client page as an "official beta"
Similar in fashion to #232
=> Add jellyfin-vue to client list

docs/general/server/media/shows.md
Documentation was wrong, naming a series with an IMDb is is not supported. See https://github.com/jellyfin/jellyfin/issues/7905#issuecomment-1153748204
Fixes jellyfin/jellyfin#7905
=> Remove suggestion to name Series with an imdbid

docs/general/administration/installing.md, src/data/downloads.tsx
I recently updated the Downloads page to use the newer deb822 format.
This pull request...
* makes the URL for the GPG key on the Download page work for both Debian and Ubuntu instead of being hardcoded for Ubuntu (they're currently both using the same key, so it's a bit of a moot point, but it's a potential source of confusion if the Debian and Ubuntu repos are changed to use different keys)
* updates the "Installing Jellyfin" page from the "Administration" section of the docs to match the instructions on the Downloads page
=> More updates for Debian/Ubuntu installation

docs/general/administration/installing.md
On the latest version of Raspberry Pi OS / Raspbian on a RPi 4, I'm able to use rootless Podman + crun to run jellyfin with the official image and get hardware accelerated encoding, so it seems like this note is out of date. The linuxserver image has apparently [switched](https://github.com/linuxserver/docker-jellyfin#versions) to using the official build's ffmpeg5, so the differences between the two images may be much smaller nowadays.
I'm using this command to run jellyfin after `sudo apt install podman crun`:
```sh
podman run \
--detach \           
--label "io.containers.autoupdate=image" \
--name jellyfin \
--publish 8096:8096/tcp \
--rm \
--user $(id -u):$(id -g) \
--userns keep-id \
--mount type=bind,source=/mnt/media/jellyfin/cache,destination=/cache \
--mount …
```
=>  Remove note about RPi and non-official images

.github/workflows/build.yml
The deployment task would sometimes fail when an existing deployment is in progress. Adding the concurrency option to the workflow should resolve this as only one instance of the job can run at any time.
=> Fix GitHub page deployment after multiple merges in a small timeframe

docs/general/administration/installing.md
Add optional `extra_hosts:` argument to docker-compose example, which is necessary to pass docker healthcheck when running in host network mode.  Otherwise results in false-positive "unhealthy" warning in `docker container ls` output, as localhost is unresolved without setting host.docker.internal:host-gateway.  At least, this is the case for me on linux, running:
~/self-hosted/jellyfin
⟩ pacman -Q | grep docker
docker 1:20.10.21-1
docker-compose 2.12.2-1
~/self-hosted/jellyfin
⟩ pacman -Q | grep container
containerd 1.6.10-1
containers-common 1:0.50.1-2
=> Update docker-compose.yml example

docs/general/server/metadata/index.md, docs/general/server/metadata/nfo.md
I took the new website as a chance to finally document the caveats I explained in jellyfin/jellyfin#5321 and a couple of more things about local .nfo files
=> Add local .nfo metadata information to docs

src/data/downloads.tsx
This should hopefully make things easier for new users who might be offput or confused by how complex the install instructions are.
The script is visible at https://repo.jellyfin.org/install-debuntu.sh
I'm game to move it somewhere else more "visible", or just leave it there in the root of the actual repository, depending on preferences. The caveat of this is that the selection of Ubuntu/Debian releases and architectures is static in the file, so version-controlling it would make quick changes harder, but I'm flexible.
=> Add curl-bash type installer type for Debuntu

docs/general/installation/linux.md
Jellyfin version listed in the tutorial is out of date, which causes an error 404 when attempting to access the archives.
=> Update jellyfin version listed in tutorial

docs/general/server/media/movies.md
Clarify that for multiple movie versioning to work, the filename prefix needs to be a perfect match to the folder name.
=> Clarify requirements for multiple movie versions

src/data/clients.ts
Replaces the TestFlight link with the App Store link. I wonder if we can/should move it up to be recommended though.
=> Update link on Swiftfin

docusaurus.config.js, src/pages/andtv-privacy.md
We've updated the privacy policy links on Google Play some time ago and this page is no longer needed
=> Remove andtv-privacy page

docs/general/contributing/source-tree.md
They're quite outdated and there is no interest from the Android team to update in docs. Might make sense to add those structures to the README's though
=> Remove Android and Android TV from source tree page

docs/general/administration/hardware-acceleration.md
Command fails with comment.
```
❯ docker run -d \
--volume /path/to/config:/config \
--volume /path/to/cache:/cache \
--volume /path/to/media:/media \
--user 1000:1000 \
--group-add="122" \ # Change this to match your system
--net=host \
--restart=unless-stopped \
--device /dev/dri/renderD128:/dev/dri/renderD128 \
--device /dev/dri/card0:/dev/dri/card0 \
jellyfin/jellyfin
docker: invalid reference format.
See 'docker run --help'.
zsh: command not found: --net=host
```
=> comment in docker command should be removed

docs/general/server/live-tv/setup-guide.md
Without this extra step, users cannot successfully setup legacy HDHomeRun tuners by following the instructions
=> Add Legacy HDHomeRun info to Live TV setup-guide.md

docs/index.md
Updated link for generic Linux in the introduction to match its new location in the Linux installation documentation.
=> Link update

docusaurus.config.js
This PR targets the new "developers" branch so we don't update the production site until these changes are more stable.
-----
This change updates the header navigation to left align the primary pages and right align secondary pages. It also changes the "Downloads" page to be the first item, because that's the most important page!
=> Update header navigation

docusaurus.config.js, package-lock.json, package.json, redirects.js
This PR targets the developers branch.
----
With this PR the classic preset is removed in favor of manual plugin/theme configurations in preparation for a second blog.
This isn't strictly necessary for multi-blog etc. but it makes the config easier to read when we do, it also shaves of _some_ of the other plugins we don't use from the dependency graph which should help a bit with the node_modules folder size.
Other changes include:
- Move the redirects for the redirect plugin to their own file (easier to maintain that way)
- Add `@type` comments for IDE assistance to plugins/themes
- Add second developer blog (commented out) to confirm multi blog works (and it does, even creates a separate RSS feed)
=> Replace @docusaurus/preset-classic with manual plugin configurations

redirects.js, src/pages/contribute.tsx
also fixed the link in the /contributing page.
=> Add redirects for developer documents moved from main docs

docs/general/administration/troubleshooting.md
Expanded and revised the documentation on debug logging to include the case where an installation has the optional 'logging.json' file present. Also generally revised and clarified language, added a link to the configuration directory documentation, and added instructions for disabling debug logging.
=> Update Debug Logging Documentation

docs/general/installation/linux.md
The 10.8.8 links are dead and I noticed the ffmpeg version was quite outdated too
=> Update Jellyfin and Jellyfin FFmpeg versions in Linux install page

src/components/home/ClientSection.module.scss, src/components/home/ClientSection.tsx, src/pages/downloads/clients/index.tsx
This PR:
- Allows you to click on all of the client icons on the homepage except web.
- Persists the filters on the client page into the URL search param.
I excluded web from the clickable links because it would either show an empty page, or, if showing all options would mislead users into thinking jellyfin-vue was the main web client.
=> Make client icons on homepage clickable

docs/general/server/media/movies.md
As discussed on the General Chat, this was a confusing point to me, as this seems to imply such tags were only available in folders.
=> Explicitly mention provider identifiers in file names

docs/general/installation/container.md
The mount label was missing, resulting in an unreadable media filesystem. Relabeling to private fixed the issue. Tested on RHEL 9.1
=> Fix podman instructions for SELinux

docs/general/networking/apache.md
Hello,
while using my deployment with the configuration provided in the official documentation I noticed that certificate renewals (I am using acme.sh) were broken because the HTTP to HTTPS upgrade causes the URL to be malformed. Assuming my domain is example.com, the validation process of Let's Encrypt would get redirected to https://example.com.well.known/... which resulted in the following error message:
[Sat 04 Mar 2023 01:32:41 AM CET] _example.com_:Verify error:_<IP>_: Fetching https://_example.com_.well-known/acme-challenge/_<challenge-path>_: Invalid host in redirect target
Adding the trailing slash fixed this misbehavior.
=> Fix HTTP -> HTTPS redirect for Let's Encrypt to work

.github/workflows/build.yml, .github/workflows/lint.yml
Because #449 `Update actions/checkout action to v3.4.0` actually provides changelog information and is more meaningful than #448 `Update actions/checkout digest to 24cb908`
Also getting duplicate PRs for actions/checkout is kind of annoying.
=> Update workflow actions to specify full version

docs/general/installation/linux.md
Adapts the installation instructions to the ones from the downloads page:
* Remove extrepo commands
* Add debuntu install script documentation
* Add Gentoo instructions
* Bump FFmpeg version in examples
* Formatting
=> Adapt install documentation to download documentation

docs/general/installation/container.md
Confirmed to work with v6.11.5.
See also: https://forums.unraid.net/topic/118437-there-is-no-template-repositories-in-my-docker-setting-page/#comment-1083593
=> Update unRaid installation instructions

docs/general/administration/hardware-acceleration/amd.md, docs/general/administration/hardware-acceleration/intel.md, docs/general/administration/hardware-acceleration/nvidia.md
- JSL and EHL are 10th Gen, no AV1 decoding.
- Update the link of `onevpl-intel-gpu` on Arch Linux.
- Add a workaround for the upstream issue `CUDA_ERROR_NO_DEVICE` in Docker.
- Add more 'sudo' for verifying drm render node.
=> Update HWA instructions for Intel and NVIDIA

content/developers/docs/index.md, content/developers/pages/index.scss, content/developers/pages/index.tsx, docusaurus.config.js
(merged to developers branch)
Definitely not my best work but good enough for now. The developer index redirects to the docs and blog. Blog posts are loaded from the blog plugin (that awful import, and yes this is the recommended way). The docs/more resources sections will be updated over time when we have more content.
=> Add index page for developers site

docusaurus.config.js, scripts/data/jellyfin-web-urls.json
Fixes an issue where the `subtitles.html` link in web in versions 10.8 and below is not redirected correctly.
Fixes https://github.com/jellyfin/jellyfin-web/issues/4410
=> Fix subtitles link redirect

docs/general/server/media/excluding-directory.md
Added a page to document the usage of `.ignore` files. Also included a notice about it currently not working for certain directories.
=> Added directory exclusion docs page

docs/general/administration/hardware-acceleration/intel.md
Ubuntu 22.04's 5.15 kernel has a regression that was fixed in 5.16 but not back ported causing hardware acceleration to break (at least on intel). You can get this fixed without building a custom kernel by using the hardware enablement stack. I used it on my own machine to get quicksync working
=> Update docs with ubuntu 22.04 hardware acceleration fix

docs/general/style-guides/javascript.md
Fixed spelling of "ommitted" twice and included the type declaration on export.
=> Fix style guide spelling and declaration export

docs/general/administration/hardware-acceleration/intel.md
- Update docs for DoVi tone-mapping on intel
- Remove the `-p` option for `intel_gpu_top` since it's only available on newer versions
=> Update docs for DoVi tone-mapping on intel

docusaurus.config.js
It's nice we have it now but it's not relevant for most of the people visiting our website. It may also confuse users thinking we are a streaming service or provide hosted instances. Moving the status link to the footer which is in my opinion the best place for a status page link.
=> Move status link from header to footer

docs/general/administration/hardware-acceleration/amd.md, docs/general/administration/hardware-acceleration/intel.md, docs/general/administration/hardware-acceleration/nvidia.md
As pointed out by https://forum.jellyfin.org/t-official-jellyfin-documentation-prompts-the-usage-of-unsafe-flags-under-arch the arguments should be changed.
=> Switch arch pacman args from -Sy to -Syu to prevent system breakage

docs/general/administration/hardware-acceleration/amd.md
`/dev/dri/kfd` is not a valid path (at least on Arch Linux).
Changing it to `/dev/kfd` fixes AMD GPU OpenCL in docker.
=> Fix AMD GPU kfd path

docs/general/contributing/development.md
There is a typo, at the https://jellyfin.org/docs/general/contributing/development#master-branch section. The command states that dotnet-sdk-6.0 should be installed, but the project requires dotnet-sdk-7.0.
=> dotnet-sdk-6.0 -> 7.0 at contributing/development

docs/general/server/live-tv/setup-guide.md
The part about the membership fee is out of date as of March 2023, but it probably shouldn't be in here anyway. They also serve more than just the US and Canada. They have guide data for Europe and some other regions.
=> Update SchedulesDirect information

docs/general/administration/hardware-acceleration/index.md
While many people like to use these SBCs to host Jellyfin, they are underpowered and don't provide a good experience whenever transcoding is needed as a result.
This PR intends to add a warning message against using these devices for hosting Jellyfin and recommend users to use more powerful hardware.
=> Warning against using Raspberry Pis or other SBCs for hosting JF

src/components/clients/ClientDetails.tsx, src/components/common/DetailsCard.scss, src/components/common/DetailsCard.tsx, src/data/clients.ts
- Added "Help Text" to clients view.
- Added Roku help text, clarifying disclaimer on roku store that JF requires subscriptions
- mitigates https://github.com/jellyfin/jellyfin-roku/issues/507
=> Added roku disclaimer in new Subtext to clients

docs/general/server/media/external-files.md
The feature has been merged into master, but has not been released yet. The docs are ahead of time. This adds a note to avoid confusion for users.
See discussion [here](https://matrix.to/#/!YOoxJKhsHoXZiIHyBG:matrix.org/$oAMehUYdavAeJ8l5gACGcazXGTVV1idX8RNwm8EtQZA?via=bonifacelabs.ca&via=t2bot.io&via=matrix.org) for extra context. In short: The docs were released a little early, so this notes is there to avoid confusing users.
=> Add note about naming flags not being supported yet

docs/general/administration/hardware-selection.md
Prebuit NASes are a popular choice for running a media server (Thanks, Synology). However they are often underpowered.
This PR adds a warning message letting people know they should check their specs to see if it meets the recommendations.
=> Add warning for prebuilt NASes

docs/general/server/metadata/index.md
There have been a few issues opened on Jellyfin about being unable to use certain media providers. Some of these issues are caused by TMDb and TVDb being blocked in mainland China.
This PR aims to properly document this.
The warning is also in Chinese for good measure
Sampie issue: [jellyfin/#4352](https://github.com/jellyfin/jellyfin/issues/4352)
=> Add warning for metadata providers in mainland china

docs/general/installation/container.md
RemapUsers is not present in the latest Quadlet documentation and UserNS appears to be equivalent
=> Update Quadlet RemapUsers option to UserNS

docs/general/administration/configuration.md, docs/general/administration/troubleshooting.md, docs/general/clients/codec-support.md
This PR aims to document where fonts are used in JF as suggested by Niels in [jellyfin-web/#4848 (Comment)](https://github.com/jellyfin/jellyfin-web/pull/4848#issuecomment-1749998514)
The required changes will be PRed on web once this PR is merged.
=> document fonts

docs/general/installation/container.md
We do not have an official Unraid install. Removed superfluous docs in favor of sending people to the 3rd party platform maintainers.
=> Update for removal of "official Unraid" platform

docs/general/installation/linux.md, src/data/downloads.tsx
The Arch Linux "Extra" repo now has `jellyfin-server` and `jellyfin-web`.
The [Jellyfin wiki page](https://wiki.archlinux.org/title/Jellyfin) has been updated.
=> arch linux package now in extra

docs/general/installation/container.md
The current links for TrueCharts Discord server and documentation point to 404 pages.
This PR updates these links to the correct pages.
=> Update links for TrueCharts Discord and docs

docs/general/administration/hardware-selection.md
I don't really know why this is needed but apparently people mistake these for the bare minimum required to run Jellyfin.
Updating this so that (hopefully) less people get confused.
=> Clarify that the recommended specs aren't the required bare minimum

docs/general/administration/hardware-acceleration/intel.md
On my system, the Intel graphics device was assigned to `1` and running the last 2 commands that query guc/huc status resulted in an no file found error. This clarification could be useful to novice linux users.
=> Add clarification about guc/huc check tutorial

docs/general/administration/hardware-acceleration/intel.md
#719 was merged with a failing linter check. This fixes the trailing white space.
=> Remove trailing spaces

docs/general/clients/css-customization.md
The [Monochromic](https://github.com/CTalvio/Monochromic), [Kaleidochromic](https://github.com/CTalvio/Kaleidochromic) and [Novachromic](https://github.com/CTalvio/Novachromic) themes have been deprecated and are superseeded by the [Ultrachromic](https://github.com/CTalvio/Ultrachromic) theme.
=> Update deprecated community themes

docs/general/installation/linux.md, src/data/downloads.tsx
This is an attempt to clean up and streamline the various Linux package install instructions.
1. (For Debuntu) The main Downloads page now provides just the most basic instructions for using the script install; users are directed to the docs page for more advanced instructions. We don't need walls of text or commands in the quickstart.
2. The Debian/Ubuntu docs are cleaned up and unified: a) The Debian and Ubuntu sections were mostly identical, so combine them and show only the (single) relevant difference. b) Add a clear command for integrity checking the script. c) Expand some aspects of the manual process for better checking, and link to the script rather than provide a list of codenames that must be constantly updated. d) Cleans up some wording.
3. The Fedora and CentOS docs are …
=> Major cleanup of Linux install instructions

src/data/downloads.tsx
Corrects some faults with #716 
1. Missing spaces between the words "use" and "wget" and between "of" and "curl". Prettier insists I remove this extra space but that is nonsensical.
2. Link should be an `<a>` tag as markdown-style did not work.
=> Fix spacing and link in downloads

.eslintrc.json, docs/general/installation/linux.md
1. Disable Prettier as it's frustrating and Bill and I don't like it.
2. Fix a missing backtick.
3. Use the spelling "FFmpeg" consistently.
=> A few more little nitpicks

docs/general/installation/macos.md
Adds the minimum macOS version enforced by .NET 6. All current indications for .NET 8 show the same version, so this will remain current for future builds.
=> Add minimum macOS version

docs/general/server/plugins/index.md
Antennas is a a utility, not a plugin. That said, it's no longer needed since it is possible to integrate TVHeadend directly without using any plugins at all. I may write a guide in the forum for that, based off of a post from [Owen Ashurst](https://owenashurst.com/post/setting-up-live-tv-with-jellyfin-with-a-usb-august-t210-v2-tv-receiver).
=> Remove Antennas

docs/general/installation/container.md
Edited the links to the Dockerfiles to make it more clear, wich one is for LinuxServer and which one is for hotio.
=> Update container.md links to Dockerfiles

docs/general/administration/hardware-acceleration/intel.md
This pull request fixes a type in the `docs/general/administration/hardware-acceleration/intel.md` file.
'Encoding' was spelled 'Encodng'
=> Fix typo in intel.md

docs/general/administration/hardware-acceleration/amd.md
=> Update Arch Linux package URL in amd.md

package-lock.json, package.json, src/components/common/PlatformIcon.tsx, src/components/contact/DiscordCard.tsx, src/components/contact/MastodonCard.tsx, src/components/contact/MatrixCard.tsx, src/components/contact/TwitterCard.tsx, src/components/home/ClientSection.tsx, src/components/home/FreedomSection.tsx, src/pages/contribute.tsx
All icons have been renamed to use the `Si` prefix so we had to update all usages
=> Upgrade to @icons-pack/react-simple-icons 9

docs/general/administration/hardware-acceleration/index.md, docs/general/administration/hardware-selection.md
RPi 5 lacks hardware encoders altogether. This PR documents that
=> Add warning for RPi 5

docusaurus.config.ts, redirects.ts, sidebars.ts
Docusaurus v3 supports TypeScript configs. way nicer to use then spamming jsdoc everywhere
=> Convert Docusaurus configuration to TypeScript

docs/general/server/plugins/index.mdx, src/components/plugins/PluginRepositoryDetails.tsx, src/components/plugins/PluginRepositoryList.tsx, src/data/pluginRepositories.ts
Move information about plugin repositories to a structured file (pluginRepositories.ts), just like the clients and server downloads.
End-goal is to generate the plugins from this information with support for filtering. Still figuring out how I want to do that though (either on Docusaurus build or a GH actions workflow updating the data).
How the plugins documentation page it will look with this PR:
=> Move plugin repositories to src/data

docs/general/server/media/shows.md
Fixes the link from `docs/general/server/media/shows#3d-videos` to `docs/general/server/media/movies#3d-movies`
=> Fix: link from shows to movies#3d-movies

docs/general/administration/hardware-selection.md
This is one of the things that I should've done better when I initially created this guide, as people might not know that when writing this guide, the Intel "Atom" I was referring to also included chipsets from other product lines such as Celeron N5105, Pentium N6000 etc.
=> Clarify what "Atom" means in the hardware selection guide

docs/general/administration/hardware-selection.md
People for whatever reason seem to think Ryzen CPUs will cause worse encoding quality when paired with a dGPU so here we are 🤷
=> Add a note on Ryzen CPUs and hardware encoding performance

docs/general/networking/nginx.md
The trailing `/jellyfin/` in the `proxy_pass` directive causes an endless redirection loop in a web browser.
On chromium-based browsers, the error is: `This page isn't working. <domain_name> redirected you too many times. ERR_TOO_MANY_REDIRECTS.`
On firefox-based browsers, the error is: `The page isn’t redirecting properly. The browser has stopped trying to retrieve the requested item. The site is redirecting the request in a way that will never complete.`
Why does this happen? Normally in Nginx if we put trailing slash `/` at the end of the `proxy_pass` directive with a variable, it will ONLY proxy `/` to jellyfin server without the entire URI. Jellyfin then redirects to `/jellyfin` and nginx redirects `/jellyfin` to `/jellyfin/` location block which contains the which contains the …
=> Fix endless redirection loop for jellyfin in subpath nginx config.

docs/general/installation/macos.md
While installing the portable version, I found that the installation instructions were out of date and referred to when a precompiled binary was [distributed back in version 10.7 of Jellyfin](https://github.com/jellyfin/jellyfin-server-macos/releases/). Since that is no longer up to date, I've updated the instructions for the current provided source. I figured this out through some trial and error, so it might not line up with the existing installation instructions, so please let me know if anything needs to be changed :)
=> Update portable installation instructions for macOS

.github/CODEOWNERS
Probably a good practice in general as the blog is a face of the project.
=> Require core to approve blog posts

docs/general/networking/nginx.md
With this header set like this, the webOS client may show a white screen when trying to play media. See jellyfin/jellyfin-webos#205.
=> nginx: Remove Origin-Agent-Cluster header

docs/general/networking/nginx.md
Oops, just realised there are more occurrences of the header in the docs, this PR removes them as well. Follow-up to #858.
=> nginx: Remove more uses of Origin-Agent-Cluster

docs/general/installation/container.md
`setsebool` is reporting `container_use_dri_device` as an invalid boolean
`getsebool -a` shows the plural `container_use_dri_devices` as valid
container-selinux version is 2.229
=> Fix typo in podman hardware acceleration section

docs/general/installation/container.md
There was a misunderstanding regarding what we see as third party and official container distributions.
This change hopes to clarify the text on what we see as third party distributions.
Prettier also changed some small things on the page. Let me know if that is a problem.
=> Clarify third party container image distributions

docs/general/installation/linux.md, src/data/downloads.tsx, src/pages/downloads/clients/index.tsx, src/pages/downloads/server.tsx
1. Remove the "All Downloads" buttons everywhere in favour of a global link to the new repository browser.
2. Move manual downloads to the right buttons, linking to the new repo browser pages.
3. Reorganize the platforms to reflect our official support (first) followed by unofficial builds (last). Also move Docker over beside Linux in the top pill list.
4. Revamp the wording of the "Stable vs. Unstable" help to be a bit clearer and advise backups in a better way, as well as announce when new unstables will be made (Weekly).
Merge alongside #884 when cutting over the new repo.
=> Revamp the Server Downloads page for 10.9.0 prerelease

docs/general/installation/container.md
Bind mounts are better because if i manually add a file inside the mounted folder, with volumes i would need to restart the container, with bind mounts i see the new files without restarting it.
In the docker run command example we are rightfully using bind mounts, i don't know why we were not doing so with docker-compose.
=> Update docker compose example with bind mounts

docs/general/server/plugins/index.mdx, src/data/pluginRepositories.ts
This pull request adds the new [TubeArchivistMetadata](https://github.com/DarkFighterLuke/TubeArchivistMetadata) plugin to the docs page https://jellyfin.org/docs/general/server/plugins/ in the 3rd party plugins and repositories sections.
=> Add TubeArchivistMetadata plugin to the docs

src/data/downloads.tsx
Had two sets of overlaps, first with GHCR being labeled as Docker Hub, and second with the stable and unstable having the same IDs. This caused the button to duplicate when switching between stable and unstable.
=> Fix overlapping labels

src/data/clients.ts
The client is now available on all WebOS versions
=> Update WebOS client listing

docs/general/testing/server/macos.md
This add an additional path where the packaged Jellyfin.app will use.
And if this is not backed up, there will potentially be a problem when user switched back to the packaged version, as the packaged version will attempt to perform a migration from the `~/.local` path, which could potentially break current install.
=> doc: add packaged Jellyfin.app data path

src/data/pluginRepositories.ts
Updated Official unstable plugin repro link in docs to be the new `https://repo.jellyfin.org/files/plugin-unstable/manifest.json`
=> Update pluginRepositories.ts to new Plugin Repro URL

docs/general/clients/kodi.md
Considered removing the entire section but that would be confusing as the client still contains the native mode.
=> Add warning for network path deprecation in Kodi native mode documentation

docs/general/installation/linux.md
https://github.com/jellyfin/jellyfin.org/pull/453#issuecomment-1984408257
=> doc: add extrepo as alternative way to install Jellyfin on Debian

docs/general/server/plugins/index.mdx
From https://github.com/jellyfin/jellyfin-plugin-subtitleextract/issues/22
This PR adds the Subtitle Extract plugin to the documentation and also encourages new Jellyfin administrators to install them.
Honestly I think the SE plugin should be integrated into Jellyfin given the horrible experience users will get without it, but I remember seeing a PR that integrated it into Jellyfin getting closed because it relied on some side effect? Can't find the URL for it at the moment but I remember @crobibero commented on it, and he did spin it out to the SE plugin.
Finally, I'm not sure about the wording for recommending individual plugins -- I do get that some people will find this recommendation useless, but I honestly do believe that a majority if not all Jellyfin admins would want to have this …
=> Add Subtitle Extract plugin

docs/general/clients/codec-support.md
Adds ALAC (Apple Lossless) to codec list
ALAC will be used if ripping CDs in iTunes with the Lossless Compression option.
=> Add ALAC to codec list

docs/general/community-standards/_category_.yml, docs/general/community-standards/chat.md, docs/general/community-standards/commercial-support.md, docs/general/community-standards/index.md
As discussed here https://github.com/jellyfin/jellyfin-meta/discussions/69 and in Matrix chat, adding the new version of rules to be part of the docs which can them be linked on Matrix, Discord and IRC.
=> Add the revised version of chat room rules to the docs

docs/general/server/plugins/index.mdx, src/data/pluginRepositories.ts
This pull request changes TubeArchivistMetadata pointings to the new GitHub repository, since  TubeArchivist developers appreciated the work and wanted to include it in the organization itself.
=> Change TubeArchivistMetadata plugin repository references

docs/general/administration/hardware-acceleration/intel.md
In the bleeding-edge kernels, the DG2 tone-mapping is broken due to Intel driver changes. This PR added a notice about this issue to warn DG2 users not to upgrade to affected versions, as there are a few distros already pushing those versions.
Ideally, I would like compatibility issues like this to be announced in a more accessible way so that more users could see them. Kernel upgrades can happen at any time with a regular system update, and if users are unaware of this issue, they may find out that the tone-mapping is broken after upgrading and would think it is a Jellyfin issue.
=> doc: add warnings about broken driver for DG2

docs/general/administration/hardware-acceleration/intel.md
This section suggests that HD500 can transcode10bit HEVC which is not the case.
HD500 doesn't support 10bit HEVC.
The CPUs that come with HD500 are all low end models that will struggle to software decode 10bit HEVC
=> Remove HD 500 from suggestions

docs/general/clients/index.mdx
- Move inclusion as recommended client below inclusion at all
- Fix an extra parentheses in the recommended client section
- Replace the info admonition with a plain paragraph
- Updating wording for license requirement
=> Update client requirements page

docs/general/administration/configuration.md, docs/general/contributing/development.md, docs/general/installation/source.md
- Docs updated for .NET 8
- Additional Node 20 installation steps added (web project requires it and the docker image still has LTS 18.x in it)
- Add missing frontend build step
=> docs: update to .NET 8

docs/general/installation/macos.md
The original doc is a bit outdated. Updated to match the 10.9 instructions.
=> doc: update macos install doc

docs/general/installation/source.md
Docker build instructions are outdated - they refer to the main `jellyfin/jellyfin` repository while it has been changed a bit ago. This PR is meant to reflect that change.
=> Update docker build instructions

src/data/downloads.tsx, src/pages/downloads/server.tsx
This marks macOS as a ffmpeg-ready platform for upcoming 10.9, should merge after 10.9 is officially stable.
=> fix: mark macOS bundle as custom ffmpeg ready

docs/general/administration/hardware-acceleration/amd.md, docs/general/administration/hardware-acceleration/intel.md, docs/general/administration/hardware-acceleration/nvidia.md
- Update HWA docs for `jellyfin-ffmpeg6`
- Update some relocated links
- Clean the unused ROCm OpenCL docs
- Bump the minimum NVIDIA driver and glibc versions
=> Update HWA docs for jellyfin-ffmpeg6

docs/general/administration/hardware-acceleration/apple.md, docs/general/administration/hardware-acceleration/index.md, docs/general/administration/hardware-selection.md, docs/general/installation/macos.md
Update the docs to include hardware acceleration docs for Apple platforms in the upcoming 10.9 release.
=> feat: add hwa doc for apple platforms

blog/2024/05-11-jellyfin-release-10.9.0/index.mdx
Context:
- https://us.blu-raydisc.com/faqs/
- https://www.blu-ray.com/faq/#bluray_name
=> fix typo: `BluRay` -> `Blu-ray`

docs/general/administration/troubleshooting.md
1. Cleans up a lot of the wording to make it clearer.
2. Adds an example of *full* debug logging for all components, rather than the (generally pretty useless) only-our-stuff debug logs.
3. Adds warnings about the quantity of logs, and a request to compress logs before sending them to people/GitHub.
4. Use more explicit example configs rather than trying to explain it in prose.
=> Update section on debug logging

docs/general/networking/nginx.md
listen http2 directive is deprecated.
nginx -t will throw a warning
=> http2 deprecated

docs/general/about.md
Adds a bit more publicly about each core team member's additional roles.
=> Add explicit definitions of core team roles

docs/general/server/live-tv/post-process.md
author of the post process script moved from gist to repository, so changed link to reflect that
=> post process script location change

docs/general/testing/upgrades.md
Hello this is my first pull request for a documentation. This one updates the manual because upgrading from unstable to stable did not work. I would appreciate your feedback
=> fix upgrading from unstable to stable documentation for Debian/Ubuntu

docs/general/administration/hardware-acceleration/amd.md
it is not clear what each VAProfile means
Just parsing the vainfo output and setting up the correct settings might be easier.
=> translate VAProfile to Jellyfin Setting

docs/general/server/metadata/index.md
Based on the source file `jellyfin/jellyfin/MediaBrowser.Providers/Plugins/Omdb/OmdbProvider.csJellyfin`, Jellyfin uses `omdbapi.com` as a metadata provider. (And in the rest of the repo it is called `The Open Movie Database`, like in `jellyfin/jellyfin/MediaBrowser.Providers/Plugins/Omdb/OmdbItemProvider.cs`.)
[`omdbapi.com`](https://www.omdbapi.com/) calls themselves "The Open **Movie** Database".
This seems to be not affiliated with "Open **Media** Database", [omdb.org](https://www.omdb.org/).
I found it incredibly difficult to figure out who is who.
I found [this comment](https://github.com/omdbapi/OMDb-API/issues/89#issuecomment-412158872) from a guy who works for a company — JustWatch — which is in Berlin and whose product is embedded on `omdb.org` (which has roots in Germany too — …
=> Replace `Open Media Database` by `Open Movie Database`

src/data/downloads.tsx
The flatpak change came up in chat a few times
- Remove server flatpak as it is outdated (still stuck on 10.8 with no maintainer)
- Mark Arch Linux as OS Package - we don't maintain it ourselves but it is in the official arch repo
- Mark fedora as community package - rpmfusion is not a default repo on fedora
- Move Gentoo above fedora for consistent ordering (order: official - os package - community)
VSCode also decided to reformat the file because of the `"editor.formatOnSave": true` setting. I'm not gonna fight that so the diff is messy.
=> Update server downloads page

docs/general/administration/hardware-acceleration/amd.md, docs/general/administration/hardware-acceleration/intel.md
The two OpenCL interop issues on Windows have been fixed recently.
- Intel 31.0.101.5590 and newer
- AMD Adrenalin 24.5.1 and newer
=> Updated docs for Intel & AMD GPU Windows driver issues

docs/general/administration/hardware-acceleration/amd.md, docs/general/administration/hardware-acceleration/nvidia.md
Removed the repeated usage of the word "the" in the AMD and NVIDIA hardware acceleration documentation
=> Fixed 2 Typos in Hardware Acceleration Docs

docs/general/administration/hardware-acceleration/intel.md
Ubuntu 24.04 has introduced the issue. This PR updates the entry to include it.
=> Include Ubuntu 24.04 bug in the i915 arc entry

docs/general/administration/hardware-acceleration/rockchip.md
Clarify that the normal Linux instructions are also needed when installing via Docker
Fixes https://github.com/jellyfin/jellyfin/issues/11475
=> Clarify Linux RKMPP docker instructions

docs/general/administration/hardware-acceleration/amd.md, docs/general/administration/hardware-acceleration/intel.md, docs/general/administration/hardware-acceleration/known-issues.md, docs/general/administration/hardware-acceleration/nvidia.md
the list of known issues and limitations can make the page hard to read if it gets too long.
This PR moves those things into a dedicated page.
=> Add dedicated page for hwa issues

docs/general/administration/storage.md
There were two parts to the note:
1. The image extractor can't be [turned off](https://github.com/jellyfin/jellyfin/issues/2355) in Jellyfin at the moment 
2. which is causing [performance issues](https://github.com/jellyfin/jellyfin/issues/2600).
The first one, has since been renamed and it [says that the extractor can be turned off](https://github.com/jellyfin/jellyfin/issues/2355#issuecomment-853934544). The second one is closed.
Overall, I think it doesn't add anything to the docs to link to these issues here because there is already a great note warning to turn off image extraction. 
Edit: Also removed note to animostiy22's repo as the github account is 404 now.
Thanks to the maintainers for all your hard work!
=> remove outdated note about image extractor

.github/workflows/build.yml
I have no idea why the exact same action is working in web, but it should probably be changed also. Perhaps there is an issue that only arises with larger artifact sizes?? :man_shrugging:
=> Fix download artifact action

docs/general/networking/nginx.md
The section itself is not documented, has huge implications like giant storage needs, fungible alternatives that are far easier to implement without the downsides of the actual implementation and should not be recommended.
=> Removed video Cache section

docs/general/networking/index.md
Add easier IPv6 option for Chromecast
=> Chromecast network

docs/general/administration/hardware-selection.md
The issue has been fixed in the latest driver, removing this warning to declutter
=> Remove outdated warning from hardware selection

docs/general/administration/hardware-acceleration/known-issues.md
Ubuntu released patched kernel for Arc GPUs on 24.04.
=> Ubuntu released patched kernel for Arc GPUs

docs/general/administration/hardware-acceleration/amd.md, docs/general/administration/hardware-acceleration/intel.md, docs/general/administration/hardware-acceleration/nvidia.md, docs/general/administration/migrate.md, docs/general/networking/traefik.md, docs/general/networking/traefik2.md
* [`version` key is deprecated](https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete). It even issues a warning in docker compose post v1.
* `docker-compose` v1 has been totally deprecated one year ago already.
=> refactor: remove deprecated docker compose v1 mentions

docs/general/networking/nginx.md
Correcting and adjusting Nginx docs.  Jellyfin site config should not be in conf.d.  Also making adjustments to config to address common problems.  Particularly with the COOP/COEP headers causing image searching to not show images.
=> Correcting and adjusting Nginx docs

docs/general/clients/jellyfin-vue.md, docs/general/testing/web/index.md
I thought of a necessary security disclaimer while redacting the docs, and they were also applicable to the testing instructions added in #1104
=> feat(clients/vue): create deployment documentation

docs/general/administration/hardware-selection.md
Just fixing a minor typo in the `Hardware Selection` docs
=> Fixing minor typo in `hardware-selection.md`

docs/general/administration/hardware-acceleration/intel.md
Proxmox VE 8 makes passing host /devices to LXCs even simpler by integrating it in its webinterface. This adds updated instructions for Proxmox 8, while keeping the old instructions for older Proxmox versions available.
Ideally, the Proxmox docs should be moved to a separate article as they also apply to AMD via VAAPI and possibly more. However, because I didn't know a better place to put them, I left them in the intel docs for now.
=> hardware-acceleration/intel: add updated proxmox docs

docs/general/community-standards/commercial-support.md, docs/general/community-standards/servers.md, src/pages/index.tsx
With a recent uptick in people asking for help with "Jellyfin" i.e. some third party server we do not support, add this as an explicit policy and add a link on the homepage to it.
=> Add server policy and homepage link

docs/general/networking/nginx.md
why is this line not removed, when it is dangerous and obsolete?
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection, we should remove it.
=> remove  X-XSS-Protection

src/data/clients.ts
Add Jellychord to clients list
=> Add Jellychord to clients list

docs/general/administration/configuration.md, docs/general/installation/container.md
Server-side fonts are used for subtitle burn-in, so it might be of interest to users to install custom fonts there.
Apparently it's enough to mount a custom font directory into for example `/usr/local/share/fonts/custom` (the `custom` part is arbitrary name, but the primary `/usr/local/share/fonts` folder shouldn't be mounted itself as it also has `.uuid` file there, so a subdir needs to be created.
And once that's done, the fontcache will apparently be automatically updated on container restart. So that just works out of the box with no changes to Jellyfin required at all.
Also did some changes to section where font types are explained.
> How to install them depends on the operating system **or container being used**.
This is meant to both suggest people to look into Docker docs if they …
=> Explain how to install subtitles in Docker

docs/general/administration/hardware-acceleration/intel.md, docs/general/administration/hardware-selection.md
As discussed on matrix earlier, Intel 10th gen and older are losing support for QSV.
Updates documentation to not recommend 10th gen and older for iGPU
=> Add deprecation notice for Intel <11th gen

docs/general/administration/hardware-selection.md
Reword a warning for 7th to 10th gen in hardware selection to make it more clear
=> Reword hardware selection warning

src/data/clients.ts
First of all - thank you all for your hard work on Jellyfin! It really is a great piece of software 🙌🏽 
I'm the developer of the [Manet](https://tilo.dev/manet/) music app for iOS and got sent a link to [this form post](https://forum.jellyfin.org/t-ios-carplay-client-for-music-manet?pid=22475#pid22475) that suggests that you might accept paid apps for the jellyfin.org website, so I thought I'd send this PR to open the discussion about being added.
=> Add Manet to the clients list

docs/general/clients/kodi.md
Reverts jellyfin/jellyfin.org#1173
=> Revert "Remove native mode from kodi document"

blog/2024/10-26-jellyfin-release-10.10.0/index.mdx, docs/general/administration/backup-and-restore.md, docs/general/testing/upgrades.md, docs/index.md
Adds a new page on backups and restoration, and reference it from the other places that reference this (latest blog post, the testing docs, and the index page).
The paths should all be good for all official and popular platforms, but feedback welcome if required. Note that I am explicitly giving full "real" paths rather than variables to help newbies; while exceptions will always exist, I believe this is better than say `%AppDataLocal%` and then trying to explain what *that* is too.
=> Add backup and restore guide to documentation

docs/general/installation/linux.md, docs/general/networking/fail2ban.md
`sudoedit` is safer than running `nano` with `sudo`. I changed the 3 entries I could find that had `sudo nano` to `SUDO_EDITOR=nano sudoedit`
=> Change sudo nano to sudoedit

docusaurus.config.ts
Some services are still caching our old social.png with the old logo. Updating the URL with a cache buster should solve this.
=> Update social.png in meta tags to fix cache on some services

docs/general/community-standards/servers.md
For the latter, this is very hard until we permit proper server branding, so let's just remove it for now.
=> Add bit about login disclaimer and remove name ref

docs/general/networking/fail2ban.md
Hey Jellyfin team,
I wanted to suggest adding a setup guide to the Jellyfin documentation that covers using Fail2Ban for users who are running Jellyfin behind a reverse proxy on a separate upstream server. In my current setup, I have Jellyfin running in a Docker container on a local server, but it's accessible to the internet through an upstream reverse proxy server. 
In my experience, trying to block IPs with Fail2Ban on the Jellyfin host didn’t work effectively because Docker’s internal networking can bypass the host’s `iptables` rules, allowing banned IPs to still reach Jellyfin.
So I set up Fail2Ban on the Jellyfin host to automatically ban IP addresses on the upstream server using `iptables` whenever unauthorised login attempts are detected.
I’ve put together a basic guide that walks …
=> ADD: Fail2ban guide for IP blocking on upstream server to Fail2ban guide (useful if jellyfin is hosted behind an upstream reverse proxy).

docs/general/administration/configuration.md
None of these I could find in the jellyfin server master branch using GH code search
=> Remove non-existent configuration options

docs/general/installation/container.md
https://github.com/jellyfin/jellyfin/pull/11162 (first in 10.9.0) moved the Dockerfile from the main repository to jellyfin-packaging.
=> Fix obsolete official Dockerfile URL

docs/general/administration/hardware-acceleration/rockchip.md
Summarizing the list of steps needed to enable HWA for Rockchip VPU inside LXC container. Primarily used in case of Proxmox setup on ARM hosts - not supported by Proxmox!
=> Adding LXC section for Rockchip VPU HWA Tutorial

docs/general/server/media/shows.md
Noticed this wasn't documented anywhere, so added it.
=> TV Shows: Document "Specials in Seasons" feature

docs/general/administration/hardware-acceleration/amd.md, docs/general/administration/hardware-acceleration/intel.md, docs/general/administration/hardware-acceleration/known-issues.md
To make ARC Battlemage GPUs and Xe kernel driver relevant.
=> Update HWA docs for the latest GPUs

docs/general/administration/hardware-acceleration/amd.md
This new link isn't exactly to the product spec and seems like it may also be fragile. But the [actual AMD product spec](https://www.amd.com/en/products/specifications/processors.html) doesn't seem to list codec support anymore, so there's that
=> Replace broken link to AMD product specs for video encoding support

docs/general/server/media/movies.md
Adds a section about splitting movies into multiple parts, adapted from the multi-part shows section.
=> Add movies split across multiple parts

docs/general/networking/index.md
The path was set to the default LE live certificate, but of course the previously generated self-signed certificate has to be used to create the PFX file.
=> Fix self-signed certificate path

docs/general/server/media/movies.md
Reverts #1096
The documentation for multiple version sorting was updated to address sorting [issues](https://github.com/jellyfin/jellyfin/issues/12129) in version 10.9. However, these issues were resolved by #[12626](https://github.com/jellyfin/jellyfin/pull/12626), which was released in server version 10.10. Multiple version sorting now behave as they did prior to 10.9.
=> Revert "update movie version sorting"

docs/general/networking/nginx.md
The CSP config give for the NGINX HTTP reverse-proxy blocks loading of all fonts because of the default CSP rule. Added a font-src header to allow loading of fonts from the server.
=> Fixing font errors for NGINX HTTP reverse-proxy

.github/workflows/build.yml
Adds a condition to avoid publishing to cloudflare on push to master
Fixes #1253
=> Add check to avoid publishing to cloudflare when already publishing to github pages

docs/general/networking/nginx.md
Add explanation of using systemd-resolved as well as docker containers.
Fixes #634
=> correct systemd-resolved related nginx config

docs/general/administration/hardware-acceleration/rockchip.md
That parameter in the command provided will cause permission issues even though those devices are accessible by the user provided in host. To use a non-root user requires extra config but let's remove the outright wrong config for now.
=> Remove user setting for rkmpp docker

docs/general/server/media/movies.md
Clarify movies structure by explicitly stating that loose media or subdirectory structure as defined in this document is required for proper media identification.
Fixes #942
=> Update movie folder structure 

docs/general/networking/nginx.md
Removing Nginx image caching.  Not needed.  As documented, doesn't cache all image endpoints.
=> Additional Nginx doc cleanup

src/data/clients.ts
This adds the recently added macOS support for the music player Manet on the clients page.
The macOS client requires the in-app subscription, so not sure if you still want to have it on the website? I'll mention it here so we can discuss it at least so you don't get surprised by it 😊
=> Update Manet to include the MacOS platform

docs/general/installation/container.md
Explicitly tell users to not use containers on Windows or macOS.
Using containers on these platforms can be hard to troubleshoot and will lead to an inferior setup (eg. no hw accel)
=> Add warning for containers on not linux

docs/general/server/plugins/index.mdx
Kitsu has changed their URL. This PR updates it
This banner will show when visiting from https://kitsu.io
=> update kitsu url

docs/general/networking/fail2ban.md
Existing fail2ban regex doesn't match failed login attempts because the IP address is [not quoted](https://github.com/jellyfin/jellyfin/blob/317d7a9f4f76dbd964e2649ed4b7d03d3e68ca9d/Jellyfin.Server.Implementations/Users/UserManager.cs#L488) in the log messages.
=> Fix fail2ban regex

docs/general/administration/troubleshooting.md
Docs PR for https://github.com/jellyfin/jellyfin/pull/13222
=> Remove mention of automatic port forwarding

blog/2025/02-28-ios-1.6/index.mdx, blog/2025/03-01-ios-1.6/index.mdx, blog/authors.yml
Adds a blog post for the Jellyfin for iOS 1.6.0 release.
Marked as draft so we can publish when the app release is ready.
Preview link for the post: https://0762e047.jellyfin-org.pages.dev/posts/ios-v1.6.0
=> Add Jellyfin iOS 1.6.0 post

docs/general/testing/server/index.md
Found a dead link on the site [Testing Jellyfin Server](https://jellyfin.org/docs/general/testing/server/) for the Upgrade & Downgrade documentation.
I've fixed this issue in this commit.
=> Fix dead link to Upgrade and Downgrade documentation

docs/general/networking/fail2ban.md
I found that the regex as posted in the Definition section on the site does not work. I do not know if this is due to recent changes in how Jellyfin server logs failed IP addresses, but the current failregex does not work out of the box.
The difference is the addition of a " before and after the ADDR portion, because the IP address is enclosed in quotation marks in the log, so the " will match those characters. Without it, I was getting no matches.
=> fix failregex in fail2ban.md

docs/general/networking/nginx.md
Since NGINX > 1.25 is depreciated, move around the logic
=> move around the listening directive

docs/general/clients/codec-support.md
Updated documentation to show that Swiftfin supports AV1 and VP9, as found in my own testing and in Swiftfin's [documentation](https://github.com/jellyfin/Swiftfin/blob/main/Documentation/players.md).
=> Updated Swiftfin codec support docs

docs/general/clients/web-config.md
The link to the stable default web config file is probably meant to point to the latest release, correct?
If this was otherwise intentionally left at 10.8.z, please disregard this PR
=> use url of 10.10.z branch in web-config.md

docs/general/server/live-tv/setup-guide.md
The README for `shuaiscott/zap2xml` was updated to mark it as deprecated on November 19, 2024 [1]. Additionally, `zap2xml` supported `tvguide` and `zap2it`. The former service has not existed for a few years, and the latter recently ceased to exist, so there's no reason to recommend this script any longer.
It was good while it lasted, R.I.P.
1. https://github.com/shuaiscott/zap2xml/commit/2c500bd14a655ebb7eaee1b9a3e7f4ceb3c46d1d
=> docs: remove zap2xml recommendation

docs/general/post-install/_category_.yml
when the index of the post install guide was removed from the PR the title also got removed
replacement of #1384
=> fix broken title for post-install guide

docs/general/clients/jellyfin-vue.md
There is still a missing anchor in [Codec support table](https://jellyfin.org/docs/general/clients/codec-support#video-compatibility) (there is no page for desktop client, which I guess was Jellyfin Media Player?) Either way, since that fix is larger in scope, I left it out for another PR.
=> Fix anchors

docs/general/server/notifications.md
Adjusting docs for notification config location.  Currently the docs still state that there is a notification tab in the Dashboard menu root.  Clarifying that notifications are configured in the webhook plugin's page now.
=> Adjusting docs for notification config location

docs/general/server/metadata/nfo.md
Add a note mentioning that album.nfo and artist.nfo are not compatible with the genre tag, as mentioned in jellyfin/jellyfin#13350.
=> Warn about a .nfo genre tag and Albums/Artists

redirects.ts, scripts/data/jellyfin-web-urls.json
Adds a redirect for a broken link used in web
Related to https://github.com/jellyfin/jellyfin-web/pull/6847
=> Fix broken intel hwa link

docs/general/post-install/transcoding/hardware-acceleration/amd.md, docs/general/post-install/transcoding/hardware-acceleration/index.md, docs/general/post-install/transcoding/hardware-acceleration/nvidia.md, docs/general/post-install/transcoding/hardware-acceleration/rockchip.md
- Updated HWA docs to match latest hardware and kernel changes
- AMD RX 9000 encoding quality improvement
- NVIDIA Blackwell speed and quality
- Rockchip RK3576 speed and quality
- Rockchip VPU load/utilization in BSP kernel 6.1.84+
=> Updated HWA docs to match latest hardware and kernel changes

docs/general/installation/advanced/community.md, src/data/downloads.tsx
The name of the Jellyfin package in the Gentoo installation instructions no longer match the names in the Gentoo repositories and wiki.
`www-apps/jellyfin` -> `www-apps/jellyfin-bin`
I've also added a link to the official wiki on the documentation.
=> Update Gentoo package name

docs/general/installation/container.md
Adding the `ghcr` to the Docker Documentation.
Fixes https://github.com/jellyfin/jellyfin-packaging/issues/60
=> mention ghcr.io images

docs/general/installation/container.md
Since the `hotio` image is not/ no longer(?) present on docker-hub, the Pull stats do not work anymore.
ghcr.io does not support accessing the pull count via API, therefore we will have to remove the pull counter for this image as well.
I previously suggested using "ghcr.io: pull count unavailable" banners that link to the repo, however we did not do that.
Therefore the only approach here is to remove this banner entirely.
=> remove hotio counter

redirects.ts
Fixes the 404 in https://github.com/jellyfin/jellyfin-expo/issues/658
We still need a better replacement with similar content to the original quick start guide, but at least this will resolve the 404 for now. The app will also need updated to directly link to this new page when it is available.
=> Fix quick start guide link redirect for iOS app

.github/CODEOWNERS, .prettierignore, docs/general/contributing/branding.md
* Updates the branding guide to specify that usage of the Jellyfin logo as a project logo or app icon is not permitted.
* Updates the branding guide to specify that unique project names that do not include "jelly" as a prefix or "fin" as a suffix are preferred.
=> Update branding guide to include logo

src/data/clients.ts
This PR contains multiple changes regarding the Clients list on the Downloads page.
1. Ordering official clients first
2. Splitting official and unofficial clients into separate lists. 
3. fixing some website-id's not being called "website"
4. minor fixes, see commits
Removal of Clients has been reverted.
=> clean clients.ts

docs/general/installation/advanced/manual.md
this should make it more clear that the given bash script will work out of box without modification, and also supplies the user and group name for the chown command. 
the $USER variable should already exist, but in trying to figure out a clear way to have the id command just spit out the username I found someone complaining that their distro doesn't set the env variable, so I figure it's best to just set it anyway.
=> Clarify bash script setup process

docs/general/post-install/transcoding/hardware-acceleration/intel.md, docs/general/post-install/transcoding/hardware-acceleration/known-issues.md
Update Intel BMG ReBAR requirement tips to the correct section. It was under the "Transcode AV1" section.
=> Update Intel BMG ReBAR requirement tips to the correct section

src/data/clients.ts
Removes `web-scrobbler` from the Client list.
Web Scrobbler is a Browser Plugin to sync your Played Music with Last.FM, Libre.fm and ListenBrainz.
Additionaly Jellyfin is supported on an Emby basis (The option is literally named "Emby/Jellyfin")
This is not a Jellyfin client,
It is a Browser Plugin also supporting "Emby/Jellyfin"
I think listing this in the clients page is quite missleading!
=> remove web scrobbler

blog/2025/10-04-sqlite-locking/index.mdx
As above, fixes a Markdown mistake.
=> Fix Interceptors link in SQLite blog post

docusaurus.config.ts
Updates the docusaurus config to support the new v4 markdown hooks.
Fixes https://github.com/jellyfin/jellyfin.org/issues/1586
=> update docusaurus config for v4

docs/general/installation/_container-docker-cli.md, docs/general/installation/_container-docker-compose.md, docs/general/installation/_container-podman.md, docs/general/installation/container.md
I am unsure if the known proxies configuration will actually work!
I found that docker does have its issues with handling `x-forwarded-for` headers.
https://github.com/docker/roadmap/issues/157
In general this PR aims to migrate the example configurations into the more secure and robust `bridge` networking mode.
Concerns like DLNA Support requiring Host mode are solved by the DLNA Documentation specifically mentioning the required `host`-networking mode.
=> Networking mode (switch from host)
